In [14]:
from pathlib import Path
import json
from collections import defaultdict
from typing import Any, Dict, Optional
import os

import pandas as pd
from datasets import Dataset, DatasetDict

# Citation Search Result Coverage and HF Dataset Prep

This notebook loads the aggregated search results, reports coverage statistics for each external source, and prepares a Hugging Face DatasetDict with one split per reference source.

## Quick Start Options:
- **Original Data Analysis**: Run cells 2-11
- **Brill KG Analysis**: Run cells 2 (helper functions) and then jump to cell 12+
- **OpenCitations (future)**: Run cells 2 and the OpenCitations section when available

In [4]:
## Helper Functions and Utilities

# These functions are used across all data sources (original, Brill, OpenCitations)

def summarize_provider(records: list[dict], provider: str) -> Dict[str, Optional[float]]:
    """Calculate coverage statistics for a given provider."""
    total_records = len(records)
    success_count = 0
    top_result_count = 0
    match_count = 0
    year_match_count = 0
    title_sims: list[float] = []
    author_sims: list[float] = []

    for record in records:
        metadata = (record.get("search_results") or {}).get(provider, {}).get("metadata_search")
        if not metadata:
            continue
        if metadata.get("success"):
            success_count += 1
        top_result = metadata.get("top_result")
        if not top_result:
            continue
        top_result_count += 1
        if top_result.get("is_match"):
            match_count += 1
        match_details = top_result.get("match_details") or {}
        title_sim = match_details.get("title_similarity")
        author_sim = match_details.get("author_similarity")
        if title_sim is not None:
            title_sims.append(float(title_sim))
        if author_sim is not None:
            author_sims.append(float(author_sim))
        if match_details.get("year_match"):
            year_match_count += 1

    mean_title_sim = float(pd.Series(title_sims).mean()) if title_sims else None
    mean_author_sim = float(pd.Series(author_sims).mean()) if author_sims else None

    return {
        "success_count": success_count,
        "success_rate": success_count / total_records if total_records else 0.0,
        "top_result_count": top_result_count,
        "top_result_rate": top_result_count / total_records if total_records else 0.0,
        "is_match_count": match_count,
        "is_match_rate": match_count / total_records if total_records else 0.0,
        "year_match_count": year_match_count,
        "year_match_rate": year_match_count / total_records if total_records else 0.0,
        "mean_title_similarity": mean_title_sim,
        "mean_author_similarity": mean_author_sim,
    }


def extract_openalex_id(raw_id: Optional[str]) -> Optional[str]:
    """Extract clean OpenAlex ID from URL."""
    if not raw_id:
        return None
    cleaned = raw_id.rstrip("/")
    return cleaned.split("/")[-1]


def build_matched_id(provider: str, ids: Dict[str, Any]) -> Optional[str]:
    """Extract provider-specific ID from ids dictionary."""
    if provider == "openalex":
        return extract_openalex_id(ids.get("openalex_id"))
    if provider == "matilda":
        return ids.get("matilda_id")
    if provider == "wikidata":
        return ids.get("wikidata_id")
    if provider == "opencitations":
        omid = ids.get("omid")
        if omid:
            cleaned = omid.rstrip("/")
            parts = cleaned.split("/")
            # Return last two segments, e.g., "br/06210459208"
            if len(parts) >= 2:
                return "/".join(parts[-2:])
        return None
    return None


def build_matched_link(provider: str, matched_id: Optional[str]) -> Optional[str]:
    """Build URL link to the matched record on provider's website."""
    search_links = {
        "openalex": "https://openalex.org/",
        "matilda": "https://matilda.science/?l=en",
        "wikidata": "https://www.wikidata.org/wiki/Wikidata:Main_Page",
        "opencitations": "https://sparql.opencitations.net/",
    }
    if matched_id:
        if provider == "openalex":
            return f"https://openalex.org/works?zoom={matched_id.lower()}"
        if provider == "matilda":
            return f"https://matilda.science/work/{matched_id}"
        if provider == "wikidata":
            return f"https://www.wikidata.org/wiki/{matched_id}"
        if provider == "opencitations":
            return f"https://api.opencitations.net/meta/v1/metadata/omid:{matched_id}"
    return search_links.get(provider)


def resolve_is_match(metadata: Optional[Dict[str, Any]]) -> bool:
    """Determine if top result is a match based on metadata."""
    if not metadata:
        return False
    top_result = metadata.get("top_result") or {}
    is_match = top_result.get("is_match")
    if is_match is not None:
        return bool(is_match)
    match_details = top_result.get("match_details") or {}
    title_similarity = match_details.get("title_similarity")
    if title_similarity is None:
        return False
    return float(title_similarity) >= 90.0


def summarize_top_result(top_result: Optional[Dict[str, Any]]) -> Dict[str, Any]:
    """Extract key fields from top result."""
    fields = ["title", "first_author", "year", "journal"]
    data = top_result or {}
    return {field: data.get(field) for field in fields}


def matched_result_to_text(m: Optional[Dict[str, Any]]) -> str:
    """Convert matched result to readable text."""
    if not m:
        return ""
    parts = []
    for k in ("title", "first_author", "year", "journal"):
        v = m.get(k)
        if v:
            parts.append(f"{k}: {v}")
    return " | ".join(parts)


def matched_result_to_markdown_json(m: Optional[Dict[str, Any]]) -> str:
    """Convert matched result to markdown-formatted JSON for Argilla."""
    if not m:
        return ""
    json_str = '```json\n' + json.dumps(m, indent=2) + '\n```'
    return json_str


def matched_link_to_markdown(m: Optional[str]) -> str:
    """Convert URL to markdown link."""
    if not m:
        return ""
    return f"[{m}]({m})"


def fix_opencitations_omid(records: list[dict]) -> None:
    """Fix OMID mapping for OpenCitations records (in-place)."""
    for record in records:
        ids = record.get("ids", {})
        omid = ids.get("omid")
        if omid:
            cleaned = omid.rstrip("/")
            parts = cleaned.split("/")
            if len(parts) >= 2:
                ids["omid"] = "/".join(parts[-2:])
        record["ids"] = ids


def build_dataset_splits(records: list[dict], providers: list[str]) -> dict[str, list[dict[str, Any]]]:
    """Build dataset splits for given records and providers."""
    split_rows: dict[str, list[dict[str, Any]]] = defaultdict(list)
    
    for record in records:
        base_row = {
            "ref_id": record.get("ref_id"),
            "original_ref_string": record.get("original_string"),
        }
        search_results = record.get("search_results") or {}
        
        for provider in providers:
            metadata = (search_results.get(provider) or {}).get("metadata_search")
            top_result = metadata.get("top_result") if metadata else None
            ids = (top_result or {}).get("ids") or {}
            matched_id = build_matched_id(provider, ids)
            
            row = {
                **base_row,
                "matched_id": matched_id or "Not Found",
                "matched_doi": ids.get("doi") or "",
                "matched_result": summarize_top_result(top_result),
                "is_match_by_similarity": resolve_is_match(metadata),
                "matched_link": build_matched_link(provider, matched_id),
            }
            split_rows[provider].append(row)
    
    return split_rows


print("✓ Helper functions loaded")

✓ Helper functions loaded

## SECTION 1: ORIGINAL DATA ANALYSIS
Skip this section if you only want to work with Brill data

### Load Original Data (CEX, EXCITE, LinkedBook)

In [5]:
DATA_PATH = Path("results_20251020_124218_limitNone_openalex_wikidata_matilda.json")
OPEN_CITATION_DATA_PATH = Path("results_20251022_161614_limitNone_opencitations.json")

with DATA_PATH.open() as f:
    records = json.load(f)
print(f"Loaded {len(records)} reference records from {DATA_PATH}")

# Load OpenCitations records (separate file)
with OPEN_CITATION_DATA_PATH.open() as f:
    records_opencitations = json.load(f)
print(f"Loaded {len(records_opencitations)} reference records from {OPEN_CITATION_DATA_PATH}")

sources = sorted({record.get("source", "unknown") for record in records})
print(f"Reference sources (main): {sources}")
providers_main = ["openalex", "matilda", "wikidata"]

# fix the omid mapping for opencitations
fix_opencitations_omid(records_opencitations)
providers_opencitations = ["opencitations"]

Loaded 759 reference records from results_20251020_124218_limitNone_openalex_wikidata_matilda.json
Loaded 759 reference records from results_20251022_161614_limitNone_opencitations.json
Reference sources (main): ['cex', 'excite', 'linkedbook']

In [6]:
## Calculate Statistics for Original Data

summary_main = {provider: summarize_provider(records, provider) for provider in providers_main}
summary_oc = {"opencitations": summarize_provider(records_opencitations, "opencitations")}
summary = {**summary_main, **summary_oc}
stats_df = pd.DataFrame(summary).T
display(stats_df)

,success_count,success_rate,top_result_count,top_result_rate,is_match_count,is_match_rate,year_match_count,year_match_rate,mean_title_similarity,mean_author_similarity
openalex,757.0,0.997365,593.0,0.781291,383.0,0.504611,385.0,0.507246,87.416526,61.976391
matilda,757.0,0.997365,421.0,0.554677,314.0,0.413702,280.0,0.368906,99.337292,67.581948
wikidata,757.0,0.997365,161.0,0.212121,124.0,0.163373,124.0,0.163373,93.428571,59.155280
opencitations,757.0,0.997365,116.0,0.152833,88.0,0.115942,89.0,0.117260,99.827586,0.000000

### Build Original Dataset

In [7]:
# Build splits for the main providers
split_rows = build_dataset_splits(records, providers_main)

# Build split for OpenCitations from its separate records file
split_rows_oc = build_dataset_splits(records_opencitations, ["opencitations"])
split_rows.update(split_rows_oc)

dataset_dict = DatasetDict({
    split: Dataset.from_list(rows)
    for split, rows in split_rows.items()
})

print(dataset_dict)
preview_split = next(iter(dataset_dict.keys()))
print(f"Preview split: {preview_split}")
dataset_dict[preview_split][:5]

DatasetDict({
    openalex: Dataset({
        features: ['ref_id', 'original_ref_string', 'matched_id', 'matched_doi', 'matched_result', 'is_match_by_similarity', 'matched_link'],
        num_rows: 759
    })
    matilda: Dataset({
        features: ['ref_id', 'original_ref_string', 'matched_id', 'matched_doi', 'matched_result', 'is_match_by_similarity', 'matched_link'],
        num_rows: 759
    })
    wikidata: Dataset({
        features: ['ref_id', 'original_ref_string', 'matched_id', 'matched_doi', 'matched_result', 'is_match_by_similarity', 'matched_link'],
        num_rows: 759
    })
    opencitations: Dataset({
        features: ['ref_id', 'original_ref_string', 'matched_id', 'matched_doi', 'matched_result', 'is_match_by_similarity', 'matched_link'],
        num_rows: 759
    })
})
Preview split: openalex

{'ref_id': ['cex_BIO-GEN-MOL_9_1',
  'cex_BIO-GEN-MOL_9_0',
  'cex_BIO-GEN-MOL_9_3',
  'cex_BIO-GEN-MOL_9_2',
  'cex_BIO-GEN-MOL_9_4'],
 'original_ref_string': ['L R Leddy, R E Holmes. Chondrosarcoma of bone. Cancer Treat Res. 2014. Vol. 162',
  'A Y Giuffrida, J E Burgueno, L G Koniaris, J C Gutierrez, R Duncan, S P Scully. Chondrosarcoma in the United States (1973 to 2003): an analysis of 2890 cases from the SEER database. J Bone Joint Surg Am. 2009. Vol. 91',
  'E Lhuissier, C Bazille, J Aury-Landas, N Girard, J Pontin, M Boittin, K Boumediene, C Baugé. Identification of an easy to use 3D culture model to investigate invasion and anticancer drug response in chondrosarcomas. BMC Cancer. 2017. Vol. 17',
  'N Girard, C Bazille, E Lhuissier, H Benateau, A Llombart-Bosch, K Boumediene, C Baugé. 3-Deazaneplanocin A (DZNep), an Inhibitor of the Histone Methyltransferase EZH2, Induces Apoptosis and Reduces Cell Migration in Chondrosarcoma Cells. PloS One. 2014. Vol. 9. pp. e98176',
  'J Puppe, R Drost, X Liu, S A Joosse, B Evers, P Cornelissen-Steijger, P Nederlof, Q Yu, J Jonkers, M van Lohuizen, A M Pietersen. BRCA1-deficient mammary tumor cells are dependent on EZH2 expression and sensitive to Polycomb Repressive Complex 2-inhibitor 3-deazaneplanocin. A. Breast Cancer Res. 2009. Vol. 11. pp. R63'],
 'matched_id': ['W322718260',
  'W2098245740',
  'W2737276581',
  'W1983545974',
  'W2133743991'],
 'matched_doi': ['',
  'https://doi.org/10.2106/jbjs.h.00416',
  'https://doi.org/10.1186/s12885-017-3478-z',
  'https://doi.org/10.1371/journal.pone.0098176',
  'https://doi.org/10.1186/bcr2354'],
 'matched_result': [{'first_author': 'Lichtenstein',
   'journal': 'PubMed',
   'title': 'Chondrosarcoma of Bone.',
   'year': 1943},
  {'first_author': 'Giuffrida',
   'journal': 'Journal of Bone and Joint Surgery',
   'title': 'Chondrosarcoma in the United States (1973 to 2003): An Analysis of 2890 Cases from the SEER Database',
   'year': 2009},
  {'first_author': 'Lhuissier',
   'journal': 'BMC Cancer',
   'title': 'Identification of an easy to use 3D culture model to investigate invasion and anticancer drug response in chondrosarcomas',
   'year': 2017},
  {'first_author': 'Girard',
   'journal': 'PLoS ONE',
   'title': '3-Deazaneplanocin A (DZNep), an Inhibitor of the Histone Methyltransferase EZH2, Induces Apoptosis and Reduces Cell Migration in Chondrosarcoma Cells',
   'year': 2014},
  {'first_author': 'Puppe',
   'journal': 'Breast Cancer Research',
   'title': 'BRCA1-deficient mammary tumor cells are dependent on EZH2 expression and sensitive to Polycomb Repressive Complex 2-inhibitor 3-deazaneplanocin A',
   'year': 2009}],
 'is_match_by_similarity': [False, True, True, True, True],
 'matched_link': ['https://openalex.org/works?zoom=w322718260',
  'https://openalex.org/works?zoom=w2098245740',
  'https://openalex.org/works?zoom=w2737276581',
  'https://openalex.org/works?zoom=w1983545974',
  'https://openalex.org/works?zoom=w2133743991']}

In [ ]:
import os
from huggingface_hub import login

hf_token = os.environ.get("HF_TOKEN")
login(token=hf_token)

# Push to Hugging Face Hub
dataset_dict.push_to_hub("yurui983/citation_linking", private=False)

Creating dataset: citation_linking_openalex

/opt/homebrew/Caskroom/miniforge/base/envs/citation_index/lib/python3.11/site-packages/argilla/datasets/_resource.py:264: UserWarning: Workspace not provided. Using default workspace: default id: d4a1881b-5e03-4d0b-b42e-d18e4f94b1af
  warnings.warn(f"Workspace not provided. Using default workspace: {workspace.name} id: {workspace.id}")
/opt/homebrew/Caskroom/miniforge/base/envs/citation_index/lib/python3.11/site-packages/argilla/records/_mapping/_mapper.py:89: UserWarning: Keys ['metadata'] in data are not present in the mapping and will be ignored.
  warnings.warn(f"Keys {unknown_keys} in data are not present in the mapping and will be ignored.")
Sending records...: 3batch [00:12,  4.22s/batch]

Creating dataset: citation_linking_matilda

Sending records...: 3batch [00:11,  3.98s/batch]

Creating dataset: citation_linking_wikidata

Sending records...: 3batch [00:10,  3.47s/batch]

Creating dataset: citation_linking_opencitations

Sending records...: 3batch [00:10,  3.46s/batch]

### Push Original Data to Argilla

This section creates one Argilla dataset per provider split and uploads records for human annotation.

In [6]:
guidelines_markdown = """
# Annotation Guidelines: Citation Linking

## What the fields mean
- ref_id: Internal identifier of the reference.
- original_ref_string: The raw reference text extracted from the document.
- matched_id: Provider-specific ID of the candidate match (or "Not Found").
  - OpenAlex: W1234567890 (last segment of /works/W…)
  - Wikidata: Q12345
  - Matilda: last path segment in /work/<id>
  - OpenCitations: OMID last path segment (e.g., br/06210459208)
- matched_doi: DOI of the candidate match (if available).
- matched_result: Compact summary of the candidate (title, first_author, year, journal).
- is_match_by_similarity: Model’s heuristic guess (for context only).
- matched_link: Link to view the candidate on the provider site.

## What you need to do
1) Check if the candidate is the same work as the reference.
   - Compare title, first author surname, year, and DOI (if present).
   - Use matched_link to verify details on the provider page.
2) If the candidate is incorrect OR empty (matched_id = "Not Found" or no details shown), find the correct record in the same provider and paste its ID in correct_id.
3) If you believe no record exists for this reference in this provider, select “No match”.

## How to answer
- Candidate is correct:
  - is_match_correct = true
  - No match = false
  - correct_id = (leave blank)
- Candidate is incorrect but correct record exists:
  - is_match_correct = false
  - No match = false
  - correct_id = provider-specific ID (OpenAlex W…, Wikidata Q…, Matilda work id, OpenCitations OMID br/…)
- No record in this provider:
  - is_match_correct = false
  - No match = true
  - correct_id = (leave blank)

Notes:
- Minor formatting/casing differences are fine; it must be the same work.
- Provide only the ID (not a URL).
"""

In [ ]:
import os
from datasets import load_dataset

try:
    import argilla as rg
except Exception:
    raise

# Argilla configuration
ARGILLA_API_URL = os.environ.get("ARGILLA_API_URL") or 'https://argilla-route-graphia-app1-staging.apps.bst2.paas.psnc.pl/'
ARGILLA_API_TOKEN = os.environ.get("ARGILLA_API_TOKEN") or 'argilla.apikey'

client = rg.Argilla(api_key=ARGILLA_API_TOKEN, api_url=ARGILLA_API_URL)

# Annotation guidelines
guidelines_markdown = """
# Annotation Guidelines: Citation Linking

## What the fields mean
- ref_id: Internal identifier of the reference.
- original_ref_string: The raw reference text extracted from the document.
- matched_id: Provider-specific ID of the candidate match (or "Not Found").
  - OpenAlex: W1234567890 (last segment of /works/W…)
  - Wikidata: Q12345
  - Matilda: last path segment in /work/<id>
  - OpenCitations: OMID last path segment (e.g., br/06210459208)
- matched_doi: DOI of the candidate match (if available).
- matched_result: Compact summary of the candidate (title, first_author, year, journal).
- is_match_by_similarity: Model's heuristic guess (for context only).
- matched_link: Link to view the candidate on the provider site.

## What you need to do
1) Check if the candidate is the same work as the reference.
   - Compare title, first author surname, year, and DOI (if present).
   - Use matched_link to verify details on the provider page.
2) If the candidate is incorrect OR empty (matched_id = "Not Found" or no details shown), find the correct record in the same provider and paste its ID in correct_id.
3) If you believe no record exists for this reference in this provider, select "No match".

## How to answer
- Candidate is correct:
  - is_match_correct = true
  - No match = false
  - correct_id = (leave blank)
- Candidate is incorrect but correct record exists:
  - is_match_correct = false
  - No match = false
  - correct_id = provider-specific ID (OpenAlex W…, Wikidata Q…, Matilda work id, OpenCitations OMID br/…)
- No record in this provider:
  - is_match_correct = false
  - No match = true
  - correct_id = (leave blank)

Notes:
- Minor formatting/casing differences are fine; it must be the same work.
- Provide only the ID (not a URL).
"""

# Argilla settings
settings = rg.Settings(
        fields=[
            rg.TextField(name="ref_id", title="Reference ID", description="The ID of the original reference."),
            rg.TextField(name="original_ref_string", title="Reference String", description="The original reference string extracted from the document."),
            rg.TextField(name="matched_id", title="Matched ID", description="The ID of the matched record from the external provider."),
            rg.TextField(name="matched_doi", title="Matched DOI", description="The DOI of the matched record from the external provider."),
            rg.TextField(name="matched_result", title="Matched Result", description="The result of the matching process.",use_markdown=True),
            rg.TextField(name="is_match_by_similarity", title="Is Match by Similarity", description="Indicates if the match was found by similarity."),
            rg.TextField(name="matched_link", title="Matched Link", use_markdown=True, description="The link to the matched record from the external provider."),
        ],
        guidelines=guidelines_markdown,
        questions=[
            rg.LabelQuestion(
                name="is_match_correct",
                title="Is the matched result correct?",
                labels=["true", "false"],
                description="Select 'true' if the candidate matched record corresponds to the same publication as the reference (matching title, first author and year). Otherwise select 'false'.",
                required=True,
            ),  
            rg.TextQuestion(
                name="correct_id",
                title="If incorrect, provide the correct ID (only id)",
                description="When the candidate is incorrect, type the provider-specific identifier of the correct match (e.g., OpenAlex id like W1234567890). Leave blank if 'true'.",
                required=False,
            ),
            rg.LabelQuestion(
                name="This reference has no match",
                title="Does this reference have no match?",
                labels=["true", "false"],
                description="Select 'true' if the reference has no match in the this provider. Otherwise select 'false'.",
                required=True,
            ),
        ]
)

# Create Argilla datasets
dataset_for_argilla = dataset_dict

for split_name, ds in dataset_for_argilla.items():
    dataset_name = f"citation_linking_{split_name}"
    print("Creating dataset:", dataset_name)
    
    dataset = rg.Dataset(name=dataset_name, settings=settings)
    dataset.create()
    hf_dataset = dataset_for_argilla[split_name]
    records_to_log = []
    for ex in hf_dataset:
        matched_raw = ex.get("matched_result") or {}
        matched_text = (
            matched_result_to_markdown_json(matched_raw)
            if isinstance(matched_raw, dict)
            else str(matched_raw or "")
        )

        is_match_val = ex.get("is_match_by_similarity")
        if isinstance(is_match_val, bool):
            is_match_str = "true" if is_match_val else "false"
        else:
            is_match_str = str(is_match_val) if is_match_val is not None else ""

        record = {
            "ref_id": ex.get("ref_id") or "",
            "original_ref_string": ex.get("original_ref_string") or "",
            "matched_id": ex.get("matched_id") or "Not Found",
            "matched_doi": ex.get("matched_doi") or "",
            "matched_result": matched_text,
            "is_match_by_similarity": is_match_str,
            "matched_link": ex.get("matched_link") or "",
            "metadata": {"ref_id": ex.get("ref_id")},
        }
        records_to_log.append(record)

    dataset.records.log(records=records_to_log)

## Section 2: Brill KG DATA

In [8]:
# Load Brill KG results
BRILL_DATA_PATH = Path("brill_search_result_20251106_165209_limitNone_openalex_wikidata_matilda.jsonl")

# Load as JSONL (each line is a JSON record)
with BRILL_DATA_PATH.open() as f:
    content = f.read().strip()
    # Check if it's a JSON array or JSONL
    if content.startswith('['):
        records_brill = json.loads(content)
    else:
        records_brill = [json.loads(line) for line in content.split('\n') if line.strip()]

print(f"Loaded {len(records_brill)} reference records from {BRILL_DATA_PATH}")

sources_brill = sorted({record.get("source", "unknown") for record in records_brill})
print(f"Reference sources (Brill): {sources_brill}")
providers_brill = ["openalex", "matilda", "wikidata"]

Loaded 200 reference records from brill_search_result_20251106_165209_limitNone_openalex_wikidata_matilda.jsonl
Reference sources (Brill): ['brill']

In [9]:
# Build stats for Brill KG
summary_brill = {provider: summarize_provider(records_brill, provider) for provider in providers_brill}

print("=== Brill KG Statistics ===")
stats_df_brill = pd.DataFrame(summary_brill).T
display(stats_df_brill)

# Optional: If you've run the original data cells, show combined statistics
try:
    if 'summary_main' in dir() and 'summary_oc' in dir():
        stats_data = {}
        for provider, stats in summary_main.items():
            stats_data[f"original_{provider}"] = stats
        stats_data["original_opencitations"] = summary_oc["opencitations"]
        for provider, stats in summary_brill.items():
            stats_data[f"brill_{provider}"] = stats
        
        stats_df_combined = pd.DataFrame(stats_data).T
        print("\n=== Combined Statistics (Original + Brill) ===")
        display(stats_df_combined)
except:
    pass  # Skip if original data not loaded

=== Brill KG Statistics ===

,success_count,success_rate,top_result_count,top_result_rate,is_match_count,is_match_rate,year_match_count,year_match_rate,mean_title_similarity,mean_author_similarity
openalex,196.0,0.98,126.0,0.630,70.0,0.350,55.0,0.275,92.674603,52.746032
matilda,196.0,0.98,101.0,0.505,42.0,0.210,32.0,0.160,97.831683,36.801980
wikidata,196.0,0.98,41.0,0.205,11.0,0.055,8.0,0.040,74.341463,39.902439

=== Combined Statistics (Original + Brill) ===

,success_count,success_rate,top_result_count,top_result_rate,is_match_count,is_match_rate,year_match_count,year_match_rate,mean_title_similarity,mean_author_similarity
original_openalex,757.0,0.997365,593.0,0.781291,383.0,0.504611,385.0,0.507246,87.416526,61.976391
original_matilda,757.0,0.997365,421.0,0.554677,314.0,0.413702,280.0,0.368906,99.337292,67.581948
original_wikidata,757.0,0.997365,161.0,0.212121,124.0,0.163373,124.0,0.163373,93.428571,59.155280
original_opencitations,757.0,0.997365,116.0,0.152833,88.0,0.115942,89.0,0.117260,99.827586,0.000000
brill_openalex,196.0,0.980000,126.0,0.630000,70.0,0.350000,55.0,0.275000,92.674603,52.746032
brill_matilda,196.0,0.980000,101.0,0.505000,42.0,0.210000,32.0,0.160000,97.831683,36.801980
brill_wikidata,196.0,0.980000,41.0,0.205000,11.0,0.055000,8.0,0.040000,74.341463,39.902439

### Build Brill Dataset Splits

In [10]:
# Build dataset splits for Brill KG records
split_rows_brill: dict[str, list[dict[str, Any]]] = defaultdict(list)

for record in records_brill:
    base_row = {
        "ref_id": record.get("ref_id"),
        "original_ref_string": record.get("original_string"),
    }
    search_results = record.get("search_results") or {}
    for provider in providers_brill:
        metadata = (search_results.get(provider) or {}).get("metadata_search")
        top_result = metadata.get("top_result") if metadata else None
        ids = (top_result or {}).get("ids") or {}
        matched_id = build_matched_id(provider, ids)
        row = {
            **base_row,
            "matched_id": matched_id or "Not Found",
            "matched_doi": ids.get("doi") or "",
            "matched_result": summarize_top_result(top_result),
            "is_match_by_similarity": resolve_is_match(metadata),
            "matched_link": build_matched_link(provider, matched_id),
        }
        split_rows_brill[provider].append(row)

# Create a new dataset dict for Brill
dataset_dict_brill = DatasetDict({
    split: Dataset.from_list(rows)
    for split, rows in split_rows_brill.items()
})

print("Brill KG Dataset:")
print(dataset_dict_brill)
preview_split_brill = next(iter(dataset_dict_brill.keys()))
print(f"\nPreview split: {preview_split_brill}")
dataset_dict_brill[preview_split_brill][:3]

Brill KG Dataset:
DatasetDict({
    openalex: Dataset({
        features: ['ref_id', 'original_ref_string', 'matched_id', 'matched_doi', 'matched_result', 'is_match_by_similarity', 'matched_link'],
        num_rows: 200
    })
    matilda: Dataset({
        features: ['ref_id', 'original_ref_string', 'matched_id', 'matched_doi', 'matched_result', 'is_match_by_similarity', 'matched_link'],
        num_rows: 200
    })
    wikidata: Dataset({
        features: ['ref_id', 'original_ref_string', 'matched_id', 'matched_doi', 'matched_result', 'is_match_by_similarity', 'matched_link'],
        num_rows: 200
    })
})

Preview split: openalex

{'ref_id': ['brill_ee65eec1-5ba8-4449-aae0-d4cc5bd1c201_521',
  'brill_8733911d-9cc0-482e-933e-311a5dc087bf_28',
  'brill_eafa6810-4e53-4e33-8c53-7edf6cde15bc_920'],
 'original_ref_string': ['Kallendorff, C. (ed.) (2007) A Companion to the Classical Tradition. Oxford.',
  'Chronica Andrensis, ed. J. Heller, MGH SS 24: 684–773.',
  'Whittaker,  C.R.  (1980).  ‘Rural  Labour  in  Three  Roman  Provinces’,  in  P.D.A.  Garnsey  (ed.), Non-slave labour in the Greco-Roman world. Cambridge, 73–99.'],
 'matched_id': ['W2503368845', 'Not Found', 'W3174136364'],
 'matched_doi': ['https://doi.org/10.1002/9780470996775',
  '',
  'https://doi.org/10.2307/j.ctv1r07g4w.12'],
 'matched_result': [{'first_author': None,
   'journal': None,
   'title': 'A Companion to the Classical Tradition',
   'year': 2007},
  {'first_author': None, 'journal': None, 'title': None, 'year': None},
  {'first_author': 'Whittaker',
   'journal': None,
   'title': 'RURAL LABOUR IN THREE ROMAN PROVINCES',
   'year': 2020}],
 'is_match_by_similarity': [True, False, True],
 'matched_link': ['https://openalex.org/works?zoom=w2503368845',
  'https://openalex.org/',
  'https://openalex.org/works?zoom=w3174136364']}

### Extend HuggingFace Dataset with Brill Records

Load the existing dataset from the hub and append the new Brill records to each split.

In [11]:
# Load existing dataset from hub
from datasets import load_dataset, concatenate_datasets

print("Loading existing dataset from HuggingFace Hub...")
existing_dataset = load_dataset("yurui983/citation_linking")

print(f"\nExisting dataset:")
print(existing_dataset)

# Merge each split
extended_dataset = {}
for split_name in existing_dataset.keys():
    if split_name in dataset_dict_brill:
        print(f"\nExtending split '{split_name}':")
        print(f"  Original records: {len(existing_dataset[split_name])}")
        print(f"  Brill records: {len(dataset_dict_brill[split_name])}")
        
        # Concatenate the datasets
        extended_dataset[split_name] = concatenate_datasets([
            existing_dataset[split_name],
            dataset_dict_brill[split_name]
        ])
        print(f"  Total records: {len(extended_dataset[split_name])}")
    else:
        # Keep original if no Brill data for this split
        extended_dataset[split_name] = existing_dataset[split_name]

# Convert to DatasetDict
extended_dataset_dict = DatasetDict(extended_dataset)

print(f"\n=== Extended Dataset ===")
print(extended_dataset_dict)

Loading existing dataset from HuggingFace Hub...

README.md: 0.00B [00:00, ?B/s]

data/opencitations-00000-of-00001.parque(…):   0%|          | 0.00/159k [00:00<?, ?B/s]

Generating openalex split:   0%|          | 0/759 [00:00<?, ? examples/s]

Generating matilda split:   0%|          | 0/759 [00:00<?, ? examples/s]

Generating wikidata split:   0%|          | 0/759 [00:00<?, ? examples/s]

Generating opencitations split:   0%|          | 0/759 [00:00<?, ? examples/s]

Existing dataset:
DatasetDict({
    openalex: Dataset({
        features: ['ref_id', 'original_ref_string', 'matched_id', 'matched_doi', 'matched_result', 'is_match_by_similarity', 'matched_link'],
        num_rows: 759
    })
    matilda: Dataset({
        features: ['ref_id', 'original_ref_string', 'matched_id', 'matched_doi', 'matched_result', 'is_match_by_similarity', 'matched_link'],
        num_rows: 759
    })
    wikidata: Dataset({
        features: ['ref_id', 'original_ref_string', 'matched_id', 'matched_doi', 'matched_result', 'is_match_by_similarity', 'matched_link'],
        num_rows: 759
    })
    opencitations: Dataset({
        features: ['ref_id', 'original_ref_string', 'matched_id', 'matched_doi', 'matched_result', 'is_match_by_similarity', 'matched_link'],
        num_rows: 759
    })
})

Extending split 'openalex':
  Original records: 759
  Brill records: 200
  Total records: 959

Extending split 'matilda':
  Original records: 759
  Brill records: 200
  Total records: 959

Extending split 'wikidata':
  Original records: 759
  Brill records: 200
  Total records: 959

=== Extended Dataset ===
DatasetDict({
    openalex: Dataset({
        features: ['ref_id', 'original_ref_string', 'matched_id', 'matched_doi', 'matched_result', 'is_match_by_similarity', 'matched_link'],
        num_rows: 959
    })
    matilda: Dataset({
        features: ['ref_id', 'original_ref_string', 'matched_id', 'matched_doi', 'matched_result', 'is_match_by_similarity', 'matched_link'],
        num_rows: 959
    })
    wikidata: Dataset({
        features: ['ref_id', 'original_ref_string', 'matched_id', 'matched_doi', 'matched_result', 'is_match_by_similarity', 'matched_link'],
        num_rows: 959
    })
    opencitations: Dataset({
        features: ['ref_id', 'original_ref_string', 'matched_id', 'matched_doi', 'matched_result', 'is_match_by_similarity', 'matched_link'],
        num_rows: 759
    })
})

In [12]:
# Push extended dataset to HuggingFace Hub
print("Pushing extended dataset to HuggingFace Hub...")
extended_dataset_dict.push_to_hub("yurui983/citation_linking", private=False)
print("✓ Dataset updated successfully!")

Pushing extended dataset to HuggingFace Hub...

Uploading the dataset shards:   0%|          | 0/1 [00:00<?, ? shards/s]

Creating parquet from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Processing Files (0 / 0)                : |          |  0.00B /  0.00B

New Data Upload                         : |          |  0.00B /  0.00B

                                        :   5%|4         | 8.65kB /  189kB

Uploading the dataset shards:   0%|          | 0/1 [00:00<?, ? shards/s]

Creating parquet from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Processing Files (0 / 0)                : |          |  0.00B /  0.00B

New Data Upload                         : |          |  0.00B /  0.00B

                                        :  10%|#         | 29.5kB /  288kB

Uploading the dataset shards:   0%|          | 0/1 [00:00<?, ? shards/s]

Creating parquet from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Processing Files (0 / 0)                : |          |  0.00B /  0.00B

New Data Upload                         : |          |  0.00B /  0.00B

                                        :  23%|##2       | 29.5kB /  128kB

Uploading the dataset shards:   0%|          | 0/1 [00:00<?, ? shards/s]

Creating parquet from Arrow format:   0%|          | 0/1 [00:00<?, ?ba/s]

Processing Files (0 / 0)                : |          |  0.00B /  0.00B

New Data Upload                         : |          |  0.00B /  0.00B

                                        : 100%|##########|  159kB /  159kB

✓ Dataset updated successfully!

### Extend Argilla Datasets with Brill Records

Add the new Brill records to the existing Argilla datasets without deleting old records.

In [16]:
# Extend Argilla datasets with Brill records
import argilla as rg


# Argilla configuration
ARGILLA_API_URL = os.environ.get("ARGILLA_API_URL") or 'https://argilla.graphia-ssh.eu/'
ARGILLA_API_TOKEN = os.environ.get("ARGILLA_API_TOKEN") or 'argilla.apikey'

client = rg.Argilla(api_key=ARGILLA_API_TOKEN, api_url=ARGILLA_API_URL)
print("Extending Argilla datasets with Brill records...")

for split_name, ds in dataset_dict_brill.items():
    dataset_name = f"citation_linking_{split_name}"
    
    print(f"\nExtending Argilla dataset: {dataset_name}")
    print(f"  Adding {len(ds)} Brill records...")
    
    try:
        # Get existing dataset (don't create new one)
        dataset = client.datasets(name=dataset_name)
        
        # Prepare records to log
        records_to_log = []
        for ex in ds:
            matched_raw = ex.get("matched_result") or {}
            matched_text = (
                matched_result_to_markdown_json(matched_raw)
                if isinstance(matched_raw, dict)
                else str(matched_raw or "")
            )

            is_match_val = ex.get("is_match_by_similarity")
            if isinstance(is_match_val, bool):
                is_match_str = "true" if is_match_val else "false"
            else:
                is_match_str = str(is_match_val) if is_match_val is not None else ""

            record = {
                "ref_id": ex.get("ref_id") or "",
                "original_ref_string": ex.get("original_ref_string") or "",
                "matched_id": ex.get("matched_id") or "Not Found",
                "matched_doi": ex.get("matched_doi") or "",
                "matched_result": matched_text,
                "is_match_by_similarity": is_match_str,
                "matched_link": ex.get("matched_link") or "",
                "metadata": {"ref_id": ex.get("ref_id"), "source": "brill"},
            }
            records_to_log.append(record)

        # Log records (this appends to existing dataset)
        dataset.records.log(records=records_to_log)
        print(f"  ✓ Added {len(records_to_log)} records to {dataset_name}")
        
    except Exception as e:
        print(f"  ✗ Error extending {dataset_name}: {e}")
        
print("\n✓ All Argilla datasets extended successfully!")

Extending Argilla datasets with Brill records...

Extending Argilla dataset: citation_linking_openalex
  Adding 200 Brill records...

/opt/homebrew/Caskroom/miniforge/base/envs/citation_index/lib/python3.11/site-packages/argilla/records/_mapping/_mapper.py:89: UserWarning: Keys ['metadata'] in data are not present in the mapping and will be ignored.
  warnings.warn(f"Keys {unknown_keys} in data are not present in the mapping and will be ignored.")

DatasetRecords: The provided batch size 256 was normalized. Using value 200.

Sending records...: 100%|██████████| 1/1 [00:03<00:00,  3.90s/batch]

  ✓ Added 200 records to citation_linking_openalex

Extending Argilla dataset: citation_linking_matilda
  Adding 200 Brill records...

DatasetRecords: The provided batch size 256 was normalized. Using value 200.

Sending records...: 100%|██████████| 1/1 [00:04<00:00,  4.84s/batch]

  ✓ Added 200 records to citation_linking_matilda

Extending Argilla dataset: citation_linking_wikidata
  Adding 200 Brill records...

DatasetRecords: The provided batch size 256 was normalized. Using value 200.

Sending records...: 100%|██████████| 1/1 [00:03<00:00,  3.57s/batch]

  ✓ Added 200 records to citation_linking_wikidata

✓ All Argilla datasets extended successfully!

### Placeholder for OpenCitations Results

When OpenCitations results for Brill are ready, run the following cells to add them to the datasets.

In [ ]:
# TODO: When OpenCitations Brill results are available, uncomment this cell
# OPENCITATIONS_BRILL_DATA_PATH = Path("brill_opencitations_results.jsonl")
# 
# with OPENCITATIONS_BRILL_DATA_PATH.open() as f:
#     content = f.read().strip()
#     if content.startswith('['):
#         records_brill_oc = json.loads(content)
#     else:
#         records_brill_oc = [json.loads(line) for line in content.split('\n') if line.strip()]
# 
# print(f"Loaded {len(records_brill_oc)} OpenCitations records from {OPENCITATIONS_BRILL_DATA_PATH}")
# 
# # Fix OMID mapping
# fix_opencitations_omid(records_brill_oc)

In [ ]:
# TODO: Build dataset splits for OpenCitations Brill records
# split_rows_brill_oc = build_dataset_splits(records_brill_oc, ["opencitations"])
# dataset_brill_oc = Dataset.from_list(split_rows_brill_oc["opencitations"])
# 
# # Load and extend HF dataset
# existing_dataset = load_dataset("yurui983/citation_linking")
# extended_oc = concatenate_datasets([
#     existing_dataset["opencitations"],
#     dataset_brill_oc
# ])
# 
# # Update the OpenCitations split
# existing_dataset["opencitations"] = extended_oc
# existing_dataset.push_to_hub("yurui983/citation_linking", private=False)
# print("✓ OpenCitations split extended and pushed to HuggingFace")

In [ ]:
# TODO: Extend Argilla with OpenCitations
# dataset = client.datasets(name="citation_linking_opencitations")
# records_to_log = []
# 
# for ex in dataset_brill_oc:
#     matched_raw = ex.get("matched_result") or {}
#     matched_text = (
#         matched_result_to_markdown_json(matched_raw)
#         if isinstance(matched_raw, dict)
#         else str(matched_raw or "")
#     )
#     is_match_val = ex.get("is_match_by_similarity")
#     if isinstance(is_match_val, bool):
#         is_match_str = "true" if is_match_val else "false"
#     else:
#         is_match_str = str(is_match_val) if is_match_val is not None else ""
#     
#     record = {
#         "ref_id": ex.get("ref_id") or "",
#         "original_ref_string": ex.get("original_ref_string") or "",
#         "matched_id": ex.get("matched_id") or "Not Found",
#         "matched_doi": ex.get("matched_doi") or "",
#         "matched_result": matched_text,
#         "is_match_by_similarity": is_match_str,
#         "matched_link": ex.get("matched_link") or "",
#         "metadata": {"ref_id": ex.get("ref_id"), "source": "brill"},
#     }
#     records_to_log.append(record)
# 
# dataset.records.log(records=records_to_log)
# print(f"✓ Added {len(records_to_log)} OpenCitations records to Argilla")